//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace F_ChannelFinder
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChannelLogo
    {
        public int ID { get; set; }
        public byte[] Image { get; set; }
        public string ImageTag { get; set; }
        public string ChannleName { get; set; }
    }
}
